#!/bin/csh

#
# installapp
#
# Installs product "qcreports_db" in the appropriate directory
#

if ( ! -e Configuration ) then
	cp -r Configuration.default Configuration
endif

source Configuration

if ( ! ${?QCREPORTINSTALLDIR} ) then
	echo "Environment variable QCREPORTINSTALLDIR has not been defined."
	echo "It should be set to the parent directory of the QC report DB applications." 
	exit 1
endif

#
# Make report output directory, if it does not exist
#

if ( ! -e $QCREPORTOUTPUTDIR ) then
	mkdir $QCREPORTOUTPUTDIR
endif

if ( ! -e $QCARCHIVEDIR ) then
	mkdir $QCARCHIVEDIR
endif

#
# Make mgd directory, if it does not exist
#

if ( ! -e $QCMGD ) then
	mkdir $QCMGD
endif

#
# Make nomen directory, if it does not exist
#

if ( ! -e $QCNOMEN ) then
	mkdir $QCNOMEN
endif

if ( ! -e $QCNOMENARCHIVE ) then
	mkdir $QCNOMENARCHIVE
endif

#
# Make gdb directory, if it does not exist
#

if ( ! -e $QCGDB ) then
	mkdir $QCGDB
endif

#
# Copy installation files to installation directory
#

foreach i (`ls Configuration *.sh`)
	cp -r $i $QCREPORTINSTALLDIR
end

foreach i (`ls mgd/*.sql mgd/*.py`)
	cp -r $i $QCMGD
end

foreach i (`ls nomen/*.sql nomen/*.py`)
	cp -r $i $QCNOMEN
end

foreach i (`ls gdb/*.sql gdb/*.py`)
	cp -r $i $QCGDB
end

sed "s/QCHTMLSERVER/$QCHTMLSERVER/" qcr.html > qcr.html.install
rm -f $QCHTML/qcr.html
cp qcr.html.install $QCHTML/qcr.html

