#!/bin/csh

#
# Install
#

cd `dirname $0` && source ./Configuration

#cd ${QCRPTS}
#sed "s/ftp.informatics.jax.org/${FTPURL}/" qcr.html > qcr.html.new
#mv -f qcr.html.new qcr.html

#
# if running against a database other than "radar", 
# then we need to replace "radar" with the appropriate value
#

#cd ${QCMGD}
#set toEdit=`grep -l radar *`
#foreach i ($toEdit)
#sed "s/radar/${RADAR_DBNAME}/g" $i > $i.new
#mv -f $i.new $i
#end

#
# permissions
#

chmod 664 Configuration.* HISTORY *.html
chmod 775 *.sh */*.py */*.sql Install

#
# directories
#

if ( ! -d ${QCREPORTDIR} ) then
	mkdir -p ${QCREPORTDIR}
endif

if ( ! -d ${QCOUTPUTDIR} ) then
	mkdir -p ${QCOUTPUTDIR}
endif

if ( ! -d ${QCLOGSDIR} ) then
	mkdir -p ${QCLOGSDIR}
endif

if ( ! -d ${QCARCHIVEDIR} ) then
	mkdir -p ${QCARCHIVEDIR}
endif

if ( ! -d ${QCALLELEARCHIVE} ) then
	mkdir -p ${QCALLELEARCHIVE}
endif

if ( ! -d ${QCNOMENARCHIVE} ) then
	mkdir -p ${QCNOMENARCHIVE}
endif

if ( ! -d ${QCGOARCHIVE} ) then
	mkdir -p ${QCGOARCHIVE}
endif

if ( ! -d ${QCGXDARCHIVE} ) then
	mkdir -p ${QCGXDARCHIVE}
endif

if ( ! -d ${QCMTBARCHIVE} ) then
	mkdir -p ${QCMTBARCHIVE}
endif

if ( ! -d ${QCMLDARCHIVE} ) then
	mkdir -p ${QCMLDARCHIVE}
endif

