#!/bin/csh

#
# To install this product in the appropriate directory
#
# 1. cd to the parent of the installation directory (i.e. /usr/local/mgi)
# 2. cvs export -r qcreports_db-#-# qcreports_db
# 3. cd to the installation directory
# 4. cp Configuration.default Configuration
# 5. edit Configuration file
# 6. run Install
#

source Configuration

cd $QCREPORTINSTALLDIR
sed "s/ftp.informatics.jax.org/$FTPURL/" qcr.html > qcr.html.new
mv -f qcr.html.new qcr.html

chmod 444 Configuration* HISTORY *.html
chmod 550 *.sh */*.py */*.sql Install
chmod 755 output

